config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  patch "tasks/:id", to: "tasks#update"
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  delete 'tasks/:id', to: 'tasks#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    # raise
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(permit_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(permit_params)
    redirect_to task_path(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path

  end

  private

  def permit_params
    params.require(:task).permit(:title, :detail, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/26248e7d32.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>

  <%= f.check_box :completed %> completed

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%if task.completed %>
        <!-- <i class="far fa-check-square"></i> -->
        <%= check_box_tag 'completed', 1, task.completed %>
      <% else %>
        <!-- <i class="far fa-square"></i> -->
        <%= check_box_tag 'completed', 1, task.completed %>
      <% end %>
      <%= link_to task.title, task_path(task.id), {class: "lien"} %>
      <%= link_to 'destroy this task', task_path(task.id), method: :delete, data: {confirm: "delete#{task.title}?"}  %>
    </li>

  <% end %>
</ul>

<%= link_to 'add a new task', tasks_new_path, { class: 'lien'}  %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>

<%= link_to 'Edit this task', edit_task_path(@task.id)  %>

<%= @task.detail %>
<% if @task.completed %>
  <i class="fa fa-check-square-o"></i> This task is completed
<% else %>
  <i class="fa fa-square-o"></i> This task is not completed yet
<% end %>

<%= link_to 'back to list', tasks_path  %>